### ISSUE TITLE
Async implementation

### ISSUE THREAD

**Issue by Valentin-Metz** [threadexio/channels-rs#1]
Hi, your implementation works great, but could you perhaps adapt it to work with async?
Specifically a channel should be constructable from a Reader/Writer that implements either [AsyncRead](https://docs.rs/futures/latest/futures/io/trait.AsyncRead.html)/[AsyncWrite](https://docs.rs/futures/latest/futures/io/trait.AsyncWrite.html) or from its respective tokio version [AsyncRead](https://docs.rs/tokio/latest/tokio/io/trait.AsyncRead.html)/[AsyncWrite](https://docs.rs/tokio/latest/tokio/io/trait.AsyncWrite.html).
This would greatly expand the application space of this project, as most large-scale applications are built in an async context.

**Comment by threadexio** [comment]
This is planned and I am working on this currently. However there are difficulties with the rest of the codebase that makes this feature hard to implement while reducing code duplication. That said, I aim to have this implemented by version `0.9.0` while supporting both versions of the traits.

I assume you have encountered such a situation where you need an async version. For now I can only suggest the following workaround as a dirty hack until proper support is implemented:

Wrap each call to `send` or `recv` with [`tokio::task::spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html). While I know this is less than ideal, it is the only low-code solution I can think of right now.

**Comment by threadexio** [comment]
Very early and somewhat buggy support for asynchronous channels is available in the [async branch](https://github.com/threadexio/channels-rs/tree/async).

Keep in mind that version completely breaks the existing API and will require some rewriting. Also for the time being it does not pass the [test for large payloads](https://github.com/threadexio/channels-rs/blob/async/tests/test_big_data.rs). But other than that it mostly works.

Also note that for now only the `tokio` async IO traits are supported, but support for [`futures`](https://docs.rs/futures/latest/futures/) is planned.

To use the async API you need to enable the `tokio` feature flag in `Cargo.toml`, like this:

```toml
[dependencies.channels]
git = "https://github.com/threadexio/channels-rs"
branch = "async"
features = [ "tokio" ]
```

**Comment by threadexio** [comment]
Version `0.9.1` introduces the async API. Make sure to turn on the `tokio` feature of the library to enable async support.

```toml
[dependencies]
channels = { version = "0.9.1", features = ["tokio"] }
```

I close this issue now as it is finally completed.
