### ISSUE TITLE
Sender is not always automatically flushed

### ISSUE THREAD

**Issue by Valentin-Metz** [threadexio/channels-rs#2]
After upgrading from `0.10.0` to `0.11.1`, the sender does not auto-flush the stream in every situation.

**Comment by threadexio** [comment]
Try to update to v0.11.2 and see if the issue still persists.

**Comment by Valentin-Metz** [comment]
Fixed with 9337a59e260df126e33de6ef9b89fb8bf1282b26.
I have tested v0.11.2 and everything works as expected.
Much appreciated!
